ALTER TABLE accounts ADD COLUMN IF NOT EXISTS otp_code VARCHAR(6) NULL DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS otp_expires_at DATETIME NULL DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_email_verified TINYINT(1) NOT NULL DEFAULT 0;
