<?php
require_once __DIR__ . '/../app/bootstrap.php';
require_once __DIR__ . '/../app/controllers/PickupRequestController.php';

 if (!Auth::check()) { header('Location: ' . APP_URL . '/admin-private-dnstl/login.php'); exit; }
if (Auth::userRole() !== 'admin') { header('Location: ' . APP_URL . '/user-junkshop/dashboard.php'); exit; }
$requests = (new PickupRequestController())->listAdminPendingRequests();
$pageTitle = 'Pending Pickup Requests';
$activePage = 'pending-pickups';
ob_start();
?>
<div class="card border-0 shadow-sm"><div class="card-body p-4 p-lg-5"><div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><p class="eyebrow mb-1">Request monitoring</p><h2 class="fw-bold mb-2">Pending Pickup Requests</h2><p class="text-muted mb-0">Review seller pickup requests and their current status.</p></div><div class="text-end"><span class="badge bg-warning text-dark" id="pending-pickup-count"><?php echo count($requests); ?> pending</span><div class="small text-muted mt-2" id="pending-pickup-updated" aria-live="polite">Last updated just now</div></div></div><div id="pending-pickup-table" class="table-responsive"><?php if (empty($requests)): ?><div class="empty-state"><div class="display-6 text-muted"><i class="bi bi-inboxes"></i></div><h5 class="mt-3 mb-2 fw-bold">No pending pickup requests</h5><p class="text-muted mb-0">New seller requests will appear here while they await review.</p></div><?php else: ?><table class="table table-hover align-middle"><thead class="table-light"><tr><th>Reference</th><th>Seller</th><th>Materials / weight</th><th>Pickup address</th><th>Preferred pickup</th><th>Submitted</th><th>Status</th></tr></thead><tbody><?php foreach ($requests as $request): ?><tr><td class="fw-semibold"><?php echo Validator::escape($request['booking_reference']); ?></td><td><?php echo Validator::escape($request['seller_name']); ?><br><span class="small text-muted"><?php echo Validator::escape($request['seller_email']); ?></span></td><td><?php echo Validator::escape($request['materials_summary']); ?><br><strong><?php echo number_format((float) $request['estimated_total_weight'], 2); ?> kg total</strong></td><td><?php echo Validator::escape($request['pickup_address']); ?></td><td><?php echo Validator::escape($request['preferred_pickup_date']); ?><br><?php echo Validator::escape($request['preferred_pickup_time']); ?></td><td><?php echo Validator::escape(date('M d, Y g:i A', strtotime($request['created_at']))); ?></td><td><span class="status-badge pending"><?php echo Validator::escape($request['current_status']); ?></span></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div></div></div>
<script>
window.addEventListener('DOMContentLoaded', function () {
 const target = document.getElementById('pending-pickup-table'); const count = document.getElementById('pending-pickup-count'); const updated = document.getElementById('pending-pickup-updated'); const apiUrl = '<?php echo APP_URL; ?>/admin-private-dnstl/api/pickup-requests.php';
 const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[character]));
 function render(requests) { if (!Array.isArray(requests)) return; count.textContent = requests.length + (requests.length === 1 ? ' pending' : ' pending'); updated.textContent = 'Last updated ' + new Date().toLocaleTimeString([], {hour: 'numeric', minute: '2-digit', second: '2-digit'}); if (!requests.length) { target.innerHTML = '<div class="empty-state"><div class="display-6 text-muted"><i class="bi bi-inboxes"></i></div><h5 class="mt-3 mb-2 fw-bold">No pending pickup requests</h5><p class="text-muted mb-0">New seller requests will appear here while they await review.</p></div>'; return; } target.innerHTML = '<table class="table table-hover align-middle"><thead class="table-light"><tr><th>Reference</th><th>Seller</th><th>Materials / weight</th><th>Pickup address</th><th>Preferred pickup</th><th>Submitted</th><th>Status</th></tr></thead><tbody>' + requests.map(request => '<tr><td class="fw-semibold">' + escapeHtml(request.booking_reference) + '</td><td>' + escapeHtml(request.seller_name) + '<br><span class="small text-muted">' + escapeHtml(request.seller_email) + '</span></td><td>' + escapeHtml(request.materials_summary) + '<br><strong>' + Number(request.estimated_total_weight || 0).toFixed(2) + ' kg total</strong></td><td>' + escapeHtml(request.pickup_address) + '</td><td>' + escapeHtml(request.preferred_pickup_date) + '<br>' + escapeHtml(request.preferred_pickup_time) + '</td><td>' + escapeHtml(String(request.created_at || '').slice(0, 16)) + '</td><td><span class="status-badge pending">' + escapeHtml(request.current_status) + '</span></td></tr>').join('') + '</tbody></table>'; }
 if (window.EcoPickLiveUpdates) window.EcoPickLiveUpdates.startPolling({key: 'admin-pending-pickup-requests', url: apiUrl, interval: 5000, onSuccess: payload => { if (payload.success) render(payload.data.requests); }});
});
</script>
<?php
$content = ob_get_clean();
require_once __DIR__ . '/../app/views/admin_dashboard_shell.php';
